#!/usr/bin/env bash
#Script displays Best School ten times
#displays 4 bad luck
#displas on 8th line goodluck

var1="Best School"
var2="bad luck"
var3="good luck"
i=0
while [ $i -lt 10 ]; do
	if [ $i == 3 ]; then
		echo "$var2"
	elif [ $i == 7 ]; then
		echo "$var3"
	else
		echo "$var1"
	fi
	((i++))
done
