#!/usr/bin/env bash
#Script that displays numbers from 1 to 20
a4="bad luck from China"
a9="bad luck from Japan"
a17="bad luck from Italy"
i=1
while [ $i -lt 21 ]; do
	case $i in
		4)
			echo "$i" && echo "$a4";;
		9)
			echo "$i" && echo "$a9";;
		17)
			echo "$i" && echo "$a17";;
		*)
			echo "$i";;
	esac
	((i++))
done
